name: Run tests

on:
  # Make workflow callable.
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Ensure there are no syntax errors in docs/tern.ttl
        run: |
          ontotools file validate docs/tern.ttl

      - name: Ensure there are no syntax errors in docs/tern.shapes.ttl
        run: |
          ontotools file validate docs/tern.shapes.ttl

      # Comment below out. Due to blank nodes, the longturtle serializer changes the file even when no content has changed.

      # - name: Ensure tern.ttl is normalized.
      #   run: |
      #     ontotools file normalize docs/tern.ttl --fail-if-changed

      # - name: Ensure tern.shacl.ttl is normalized.
      #   run: |
      #     ontotools file normalize docs/tern.shacl.ttl --fail-if-changed
