name: Run tests

on:
  # Make workflow callable.
  workflow_call:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]
        test-case:
          - name: Check Turtle syntax - docs/tern.ttl
            command: ontotools file validate docs/tern.ttl
          - name: Check Turtle syntax - docs/tern.shapes.ttl
            command: ontotools file validate docs/tern.shapes.ttl
          - name: Check Turtle syntax - docs/tern.ecoplots.shapes.ttl
            command: ontotools file validate docs/tern.ecoplots.shapes.ttl
          - name: Check Turtle syntax - docs/meta.shapes.ttl
            command: ontotools file validate docs/meta.shapes.ttl
          - name: Check Turtle syntax - docs/tern.profile.ttl
            command: ontotools file validate docs/tern.profile.ttl
          - name: Check Turtle syntax - docs/ecoplots.profile.ttl
            command: ontotools file validate docs/ecoplots.profile.ttl

          - name: Validate shapes with meta shapes - docs/tern.ttl
            command: pyshacl -s docs/meta.shapes.ttl docs/tern.ttl
          - name: Validate shapes with meta shapes - docs/tern.shapes.ttl
            command: pyshacl -s docs/meta.shapes.ttl docs/tern.shapes.ttl
          - name: Validate shapes with meta shapes - docs/tern.ecoplots.shapes.ttl
            command: pyshacl -s docs/meta.shapes.ttl docs/tern.ecoplots.shapes.ttl
          - name: Validate shapes with meta shapes - docs/meta.shapes.ttl
            command: pyshacl -s docs/meta.shapes.ttl docs/meta.shapes.ttl

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v3

      - name: Use Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: ${{ matrix.test-case.name }}
        run: |
          ${{ matrix.test-case.command }}
